name: Windows testing Workflow

on:
  push:
    branches:
      - main
      - redesign
  workflow_dispatch:

concurrency:
  group: release_workflow
  cancel-in-progress: true

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # Checks and downloads project source code from GitHub repository

      - name: Setup environment variables
        run: cat .github/workflows/versions.env >> $GITHUB_ENV
        # Load environment variables from versions.env file

      - name: Prepare Windows environment
        run: ./scripts/prepare-windows.ps1
        shell: pwsh
        # Executes PowerShell script to prepare Windows environment

      - name: Build OLM library for Windows
        run: ./scripts/build-olm-windows.sh
        shell: bash
        # Run the Olm compiler script for cryptography if use Matrix

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build Windows Release
        run: flutter build windows --release

      - name: Get tag
        id: tag
        run: |
          echo "TAG=$(git describe --tags)" >> $GITHUB_ENV
        shell: bash

      - name: Post-build Windows operations
        run: ./scripts/build-windows.ps1
        shell: pwsh

      - name: Create Archive for Release
        run: tar -czf "tawkie-windows.tar.gz" -C build/windows/runner/Release/ .
        # Create an archive for the release and include the version in the filename
      - name: Upload Windows Release to GitHub
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "tawkie-windows.tar.gz"
          asset_name: "tawkie-windows-${{ env.TAG }}.tar.gz"
          asset_content_type: application/gzip
        # Upload the archive on the GitHub release page as an asset