name: macOS Client Build

on:
  push:
    branches:
      - main
      - redesign
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment variables
        run: cat .github/workflows/versions.env >> $GITHUB_ENV

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build macOS Release
        run: flutter build macos --release

      - name: Get tag
        id: tag
        run: echo "TAG=$(git describe --tags)" >> $GITHUB_ENV

      - name: Create DMG
        run: |
          brew install create-dmg
          create-dmg \
            --volname "Tawkie" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --icon "Tawkie.app" 200 190 \
            --hide-extension "Tawkie.app" \
            --app-drop-link 600 185 \
            "Tawkie-${{ env.TAG }}.dmg" \
            "build/macos/Build/Products/Release/Tawkie.app"

      - name: Upload macOS Release
        uses: actions/upload-artifact@v3
        with:
          name: Tawkie-macOS-${{ env.TAG }}
          path: Tawkie-${{ env.TAG }}.dmg

      - name: Upload macOS Release to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: Tawkie-${{ env.TAG }}.dmg
          asset_name: Tawkie-macOS-${{ env.TAG }}.dmg
          asset_content_type: application/x-apple-diskimage